
services:
  latex:
    build: .
    container_name: latex_compiler
    volumes:
      # Mapeia o diretório atual do host para dentro do container
      - .:/workspace
    # Executa o latexmk para compilar o arquivo desejado
    command: sleepy infinity